apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-front
  namespace: jayv-labs
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: jayv-labs.labs-rneaxc.walmartdigital.cl
    http:
      paths:
      - path: /
        backend:
          serviceName: hello
          servicePort: 80
      - path: /login
        backend:
          serviceName: auth
          servicePort: 80
