apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-back
  namespace: group-name
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
spec:
  tls:
  - hosts:
    - api.labs-fwjyss.walmartdigital.cl
    secretName: acme-crt-secret
  rules:
  - host: api.labs-fwjyss.walmartdigital.cl
    http:
      paths:
      - path: /zzz
        backend:
          serviceName: xxx
          servicePort: yyy
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: hello-back
  namespace: group-name
proxy:
  path: /
route:
  strip_path: true
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: acme-crt
  namespace: group-name
spec:
  secretName: acme-crt-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - api.labs-fwjyss.walmartdigital.cl
  acme:
    config:
    - dns01:
        provider: cf-dns
      domains:
      - api.labs-fwjyss.walmartdigital.cl